[package]
name = "halo2-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2" }
halo2_frontend = { git = "https://github.com/privacy-scaling-explorations/halo2" }
pasta_curves = "0.4.0"